### ISSUE TITLE
Need of update to 1.20.6

### ISSUE THREAD

**Issue by TheoMarque** [mfnalex/InvUnload#62]
[21:51:39 ERROR]: Error occurred while disabling InvUnload v5.0.2
java.lang.NullPointerException: Cannot invoke "java.util.HashMap.entrySet()" because "this.playerSettings" is null
        at InvUnload.jar/de.jeff_media.InvUnload.Main.saveAllPlayerSettings(Main.java:285) ~[InvUnload.jar:?]
        at InvUnload.jar/de.jeff_media.InvUnload.Main.onDisable(Main.java:84) ~[InvUnload.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:git-Paper-51]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:git-Paper-51]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:git-Paper-51]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-51]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-51]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-51]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

Until update to 1.20.6 - works fine.

**Comment by Mcklp** [comment]
New version (5.0.3) is already at spigotmc.org. 1.20.6 is working without any problems.

**Comment by mfnalex** [comment]
Fixed in 5.0.3: https://www.spigotmc.org/resources/invunload.60095/update?update=546339
